# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
additional_repos: []
all: false
black: true
bootstrap: false
check_commit_message: true
check_gettext: true
check_manifest: true
check_openapi_schema: true
check_stray_pulpcore_imports: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs_test: true
exclude_check_commit_message: false
exclude_coverage: true
exclude_deploy_client_to_pypi: false
exclude_deploy_client_to_rubygems: false
exclude_deploy_daily_client_to_pypi: false
exclude_deploy_daily_client_to_rubygems: false
exclude_deploy_to_pypi: false
exclude_docs_test: false
exclude_mariadb_test: false
exclude_test_bindings: false
issue_tracker: redmine
plugin_app_label: container
plugin_camel: PulpContainer
plugin_camel_short: Container
plugin_caps: PULP_CONTAINER
plugin_caps_short: CONTAINER
plugin_dash: pulp-container
plugin_dash_short: container
plugin_default_branch: master
plugin_name: pulp_container
plugin_snake: pulp_container
publish_docs_to_pulpprojectdotorg: true
pulp_settings:
  allowed_content_checksums:
  - sha1
  - sha224
  - sha256
  - sha384
  - sha512
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pulpprojectdotorg_key_id: aa499d7938ed
pydocstyle: true
pypi_username: pulp
redmine_project: pulp_container
test: false
test_bindings: false
test_cli: true
test_fips_nightly: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: true
test_s3: true
travis: true
travis_addtl_services: []
travis_notifications: None
update_redmine: true
verbose: false

