# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
all: false
black: false
bootstrap: false
check_commit_message: true
cherry_pick_automation: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs: false
docs_test: true
exclude_check_commit_message: false
exclude_coverage: true
exclude_deploy_client_to_pypi: false
exclude_deploy_client_to_rubygems: false
exclude_deploy_daily_client_to_pypi: false
exclude_deploy_daily_client_to_rubygems: false
exclude_deploy_to_pypi: false
exclude_docs_test: false
exclude_mariadb_test: false
exclude_test_bindings: false
plugin_app_label: container
plugin_camel: PulpContainer
plugin_camel_short: Container
plugin_caps: PULP_CONTAINER
plugin_caps_short: CONTAINER
plugin_dash: pulp-container
plugin_dash_short: container
plugin_name: pulp_container
plugin_snake: pulp_container
pulp_settings:
  private_key_path: /var/lib/pulp/tmp/private.pem
  public_key_path: /var/lib/pulp/tmp/public.pem
  token_server: http://pulp:80/token
  token_signature_algorithm: ES256
pulpcore_branch: master
pulpcore_pip_version_specifier: null
pydocstyle: true
pypi_username: pulp
redmine_project: pulp_container
stable_branch: '1.0'
test: false
test_bindings: false
test_performance: false
test_s3: false
travis: true
travis_addtl_services: []
travis_notifications: None
verbose: false

